version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp
    ports: 
      - "3307:3306"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - "3001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
